### ISSUE TITLE
Support Invitations

### ISSUE THREAD

**Issue by nateklaiber** [quicksprout/naas-api-client-python#27]
### Tasks

* [x] Add Addon models
* [x] Add Addon requests
* [x] Add AccountAddon models
* [x] Add AccountAddon requests
* [x] Add Invitation models
* [x] Add Invitation requests
* [x] Add EmailNotificationInvitationBasic request
* [x] Add EmailNotificationInvitationBasic model

**Comment by nateklaiber** [comment]
@stevecox - I've added latest models into the API client. Going to merge this in for use with the latest invitations release.

There are outstanding issues with this client, but none that would prohibit creating the invitations. I've made notes of those other items and will address them in a subsequent PR.
